#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/CleanFunctions  # Tutorial log-file functions
#------------------------------------------------------------------------------

foamListTimes -rm
rm -r 0
rm -r processor*
rm -r constant/polyMesh
rm -r system
rm -r constant
rm  log.*
rm -r dynamicCode
#------------------------------------------------------------------------------

